version: "3.9"
services:
  minecraft:
    build: 
      context: ./minecraft
      args: 
        MINECRAFT_VERSION: 1.21.7
    volumes:
      - ./minecraft-data:/minecraft-server/data
    ports:
      - 25565:25565
    environment:
      - eula=true
    stdin_open: true 
    tty: true